from app.schemas.auth import (
    RegisterRequest,
    LoginRequest,
    LoginResponse,
    ChangePasswordRequest,
    ChangeUsernameRequest,
    MessageResponse,
)
from app.schemas.user import CreateUserRequest, UserResponse, UserListResponse
from app.schemas.course import (
    CreateCourseRequest,
    UpdateCourseRequest,
    CourseResponse,
    CourseListResponse,
    CourseDetailResponse,
    CreateClassRequest,
    UpdateClassRequest,
    ClassResponse,
    ClassDetailResponse,
    CreateLessonRequest,
    UpdateLessonRequest,
    LessonResponse,
    LessonDetailResponse,
    CreateTextMaterialRequest,
    MaterialResponse,
    MaterialListResponse,
)

__all__ = [
    "RegisterRequest",
    "LoginRequest",
    "LoginResponse",
    "ChangePasswordRequest",
    "ChangeUsernameRequest",
    "MessageResponse",
    "CreateUserRequest",
    "UserResponse",
    "UserListResponse",
    "CreateCourseRequest",
    "UpdateCourseRequest",
    "CourseResponse",
    "CourseListResponse",
    "CourseDetailResponse",
    "CreateClassRequest",
    "UpdateClassRequest",
    "ClassResponse",
    "ClassDetailResponse",
    "CreateLessonRequest",
    "UpdateLessonRequest",
    "LessonResponse",
    "LessonDetailResponse",
    "CreateTextMaterialRequest",
    "MaterialResponse",
    "MaterialListResponse",
]
