import os
import time
import logging
import grpc
import asyncio
from proto import audio_pb2
from proto import audio_pb2_grpc

# Import the agent logic
from agent import ConversationalAgent

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s  %(levelname)s  %(message)s"
)
logger = logging.getLogger(__name__)

class AudioServicer(audio_pb2_grpc.AudioServiceServicer):
    """
    Implements the AudioService gRPC interface using AsyncIO.
    Integrates the ConversationalAgent to replace the simple echo.
    """

    async def StreamAudio(self, request_iterator, context):
        """
        Bidirectional streaming RPC.
        1. Receives audio chunks.
        2. Forwards them to the Agent.
        3. Yields TTS audio generated by the Agent back to the client.
        """
        peer = context.peer()
        logger.info("StreamAudio started  peer=%s", peer)
        
        # Create a thread-safe queue to bridge the Agent (threaded) and gRPC (async)
        # We use a standard queue in the agent, but we need to read it here asynchronously
        response_queue = asyncio.Queue()
        
        # Initialize Agent for this specific session
        agent = ConversationalAgent(response_queue)

        async def request_consumer():
            """Consumes audio from the client and feeds it to the agent."""
            try:
                async for chunk in request_iterator:
                    # Feed data to agent immediately
                    # This call is non-blocking; agent buffers internally
                    agent.process_audio_chunk(chunk.data)
            except grpc.RpcError as e:
                logger.info(f"Client stream closed: {e.code()}")
            except Exception as e:
                logger.error(f"Error in request consumer: {e}")

        # Start consuming requests in the background
        consumer_task = asyncio.create_task(request_consumer())

        try:
            # Main loop: yield responses generated by the agent
            while True:
                # Check if the consumer task is done (client disconnected)
                if consumer_task.done():
                    # Process any remaining messages in the queue before closing
                    if response_queue.empty():
                        break
                
                try:
                    # Wait for data from the agent (with small timeout to check task status)
                    msg_type, data = await asyncio.wait_for(response_queue.get(), timeout=0.1)
                    
                    if msg_type == "audio":
                        # Yield the audio chunk back to the caller
                        # We preserve the session_id if needed, though the original echo code did it.
                        yield audio_pb2.AudioChunk(data=data)
                    elif msg_type == "end":
                        # End of a turn, but we keep the stream open for more input
                        pass
                        
                except asyncio.TimeoutError:
                    # No data ready, loop continues to check connection status
                    continue

        except Exception as e:
            logger.error(f"Stream error: {e}")
        finally:
            # Cleanup
            consumer_task.cancel()
            logger.info("StreamAudio finished  peer=%s", peer)


async def serve():
    port = os.environ.get("GRPC_PORT", "50051")
    
    # Create Async gRPC server
    server = grpc.aio.server()
    
    audio_pb2_grpc.add_AudioServiceServicer_to_server(AudioServicer(), server)
    
    listen_addr = f"[::]:{port}"
    server.add_insecure_port(listen_addr)
    
    logger.info("Audio service listening on port %s", port)
    
    await server.start()
    await server.wait_for_termination()


if __name__ == "__main__":
    # Run the async server
    asyncio.run(serve())
