"""
gRPC AudioService implementation.

Handles bidirectional audio streaming between the browser client
and the ConversationalAgent.
"""

import asyncio
import logging

import grpc
from proto import audio_pb2

from core.conversation import ConversationalAgent

logger = logging.getLogger(__name__)


class AudioServicer:
    """
    Implements the AudioService gRPC interface using AsyncIO.
    Integrates the ConversationalAgent with RAG-powered lesson awareness.
    """

    async def StreamAudio(self, request_iterator, context):
        """
        Bidirectional streaming RPC.
        1. The FIRST message carries lesson_context (JSON) for RAG setup.
        2. Subsequent messages carry audio chunks.
        3. Agent uses RAG to retrieve relevant lesson material for each response.
        4. Buffers the complete TTS response, then yields it as one AudioChunk.
        """
        peer = context.peer()
        logger.info("StreamAudio started  peer=%s", peer)

        # Create a thread-safe queue to bridge the Agent (threaded) and gRPC (async)
        response_queue = asyncio.Queue()
        loop = asyncio.get_running_loop()

        # We'll initialise the agent after reading the first message
        agent = None
        first_message = True

        async def request_consumer():
            """Consumes audio from the client and feeds it to the agent."""
            nonlocal agent, first_message
            try:
                async for chunk in request_iterator:
                    if first_message:
                        # Extract lesson context from the first message
                        lesson_context = chunk.lesson_context or ""
                        if lesson_context:
                            logger.info(
                                "Received lesson context (%d chars) — initialising RAG",
                                len(lesson_context),
                            )
                        else:
                            logger.info("No lesson context provided — generic mode")

                        agent = ConversationalAgent(
                            response_queue, loop, lesson_context=lesson_context
                        )
                        first_message = False

                        # First message may also contain audio data
                        if chunk.data:
                            agent.process_audio_chunk(chunk.data)
                    else:
                        if agent is not None:
                            agent.process_audio_chunk(chunk.data)
            except grpc.RpcError as e:
                logger.info(f"Client stream closed: {e.code()}")
            except Exception as e:
                logger.error(f"Error in request consumer: {e}")

        # Start consuming requests in the background
        consumer_task = asyncio.create_task(request_consumer())

        try:
            # Buffer audio for a complete turn, then yield at once
            audio_buffer = bytearray()

            # Main loop: yield responses generated by the agent
            while True:
                # Check if the consumer task is done (client disconnected)
                if consumer_task.done():
                    # Flush any remaining buffered audio
                    if audio_buffer:
                        yield audio_pb2.AudioChunk(data=bytes(audio_buffer))
                        audio_buffer = bytearray()
                    # Process any remaining messages in the queue before closing
                    if response_queue.empty():
                        break

                try:
                    # Wait for data from the agent (with small timeout to check task status)
                    msg_type, data = await asyncio.wait_for(
                        response_queue.get(), timeout=0.1
                    )

                    if msg_type == "audio":
                        # Accumulate audio chunks for this turn
                        audio_buffer.extend(data)
                    elif msg_type == "end":
                        # End of a turn — send the complete WAV as one chunk
                        if audio_buffer:
                            yield audio_pb2.AudioChunk(data=bytes(audio_buffer))
                            audio_buffer = bytearray()

                except asyncio.TimeoutError:
                    # No data ready, loop continues to check connection status
                    continue

        except Exception as e:
            logger.error(f"Stream error: {e}")
        finally:
            # Cleanup
            consumer_task.cancel()
            if agent is not None:
                agent.close()
            logger.info("StreamAudio finished  peer=%s", peer)
